version: "2"
services:
  struts_vuln:
    build: ./struts_vuln
    ports:
        - "0.0.0.0:9999:8080"
    links:  
      - bsidesctf_ssh

  bsidesctf_ssh:
    build: ./bsidesctf_ssh
    environment:
      - SSH_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCqITmc0AJ1GmnvY0utw0rjqVMoJs8IymBonmHD46TlM0z3HGYL+irdEZHtQYJrl6U0ceIjVVNJU0fQSJRFu7Cy9MpHv1eJtZL/QMcbKDrQmnMj7r7YwOOvfZVE03TL1OmBsV4VN7tHW3cLwSI2i15eJ71EYbrZnNgotWgLUcpElMr/q7GAmaErGdBPml/i+KAi6ABXbty4SPTQ5FuPWlEPNGDE//PLDt4kkLgnrILzIcrlbzDO9qF9b9Nu/QhE0dH/CXAAIdiP7efUKQ9QSsvxYzamjpMNB6iNJEWcf8Uhd+9RkIIhyl0R69AcCwcoUaKwmUYlu9sS8ch1fbwLSbT bsidesctf@bsidesctf_ssh
    ports:
      - "127.0.0.1:2222:22"